/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quidditch;

import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.*;

/**
 *
 * @author Elater
 */
public class Miotly extends javax.swing.JFrame {
    
    Boolean pozycjaZaznaczona=false;
    Integer idZespolu;
    Integer idZawodnika;
    Boolean wyszukiwanie=false;
    /**
     * Creates new form Ranking
     */
    public Miotly() throws SQLException {
        initComponents();
        fillData();
        setVisible(true);
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent we) {
                int odp = JOptionPane.showConfirmDialog(null, "Czy na pewno chcesz zamknąć aplikację?", "Zamknąć?", JOptionPane.YES_NO_OPTION);
                if (odp ==JOptionPane.YES_OPTION)
                    System.exit(0);
            }
            
});
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        rankTable = new javax.swing.JTable();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 40), new java.awt.Dimension(0, 40), new java.awt.Dimension(32767, 40));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 30), new java.awt.Dimension(0, 30), new java.awt.Dimension(32767, 30));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jObraz = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jWyszukajButton1 = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jUsunButton = new java.awt.Button();
        jModyfikujButton = new java.awt.Button();
        jLabel3 = new javax.swing.JLabel();
        jComboBox = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jDodajButton = new java.awt.Button();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jRanking = new javax.swing.JMenu();
        jZawodnicy = new javax.swing.JMenu();
        jStadiony = new javax.swing.JMenu();
        jMiotly = new javax.swing.JMenu();
        jPracownicy = new javax.swing.JMenu();
        jSedziowie = new javax.swing.JMenu();
        jZnicze = new javax.swing.JMenu();
        jKary = new javax.swing.JMenu();
        jRozegrane = new javax.swing.JMenu();
        jZaplanowane = new javax.swing.JMenu();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quidditch rank");

        rankTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Szubinianka", "Polska", "Szubinland", "66"},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nazwa", "Narodowość", "Stadion", "Punkty"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        rankTable.setName("tabelaRanking"); // NOI18N
        rankTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rankTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(rankTable);

        jWyszukajButton1.setText("Wyszukaj");
        jWyszukajButton1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jWyszukajButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jWyszukajButton1ActionPerformed(evt);
            }
        });

        jUsunButton.setLabel("Usuń");
        jUsunButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUsunButtonActionPerformed(evt);
            }
        });

        jModyfikujButton.setLabel("Modyfikuj");
        jModyfikujButton.setName(""); // NOI18N
        jModyfikujButton.setPreferredSize(new java.awt.Dimension(50, 24));
        jModyfikujButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jModyfikujButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Tworzywo:");

        jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Model:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Prędkosć:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Czyja:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Masa:");

        jDodajButton.setActionCommand("Dodaj");
        jDodajButton.setLabel("Dodaj");
        jDodajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDodajButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Kolor:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jDodajButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(190, 190, 190))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jModyfikujButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jUsunButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField1)
                            .addComponent(jTextField2)
                            .addComponent(jTextField4)
                            .addComponent(jTextField5)
                            .addComponent(jTextField6))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDodajButton, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jModyfikujButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jUsunButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jRanking.setText("Ranking");
        jRanking.setBorderPainted(true);
        jRanking.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jRanking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRankingMouseClicked(evt);
            }
        });
        jMenuBar1.add(jRanking);

        jZawodnicy.setText("Zawodnicy");
        jZawodnicy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jZawodnicyMouseClicked(evt);
            }
        });
        jMenuBar1.add(jZawodnicy);

        jStadiony.setText("Stadiony");
        jStadiony.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jStadionyMouseClicked(evt);
            }
        });
        jMenuBar1.add(jStadiony);

        jMiotly.setText("Miotly");
        jMiotly.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMiotlyMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMiotly);

        jPracownicy.setText("Pracownicy");
        jPracownicy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPracownicyMouseClicked(evt);
            }
        });
        jMenuBar1.add(jPracownicy);

        jSedziowie.setText("Sędziowie");
        jSedziowie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSedziowieMouseClicked(evt);
            }
        });
        jMenuBar1.add(jSedziowie);

        jZnicze.setText("Znicze");
        jZnicze.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jZniczeMouseClicked(evt);
            }
        });
        jMenuBar1.add(jZnicze);

        jKary.setText("Kary");
        jKary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jKaryMouseClicked(evt);
            }
        });
        jMenuBar1.add(jKary);

        jRozegrane.setText("Rozegrane");
        jRozegrane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRozegraneMouseClicked(evt);
            }
        });
        jMenuBar1.add(jRozegrane);

        jZaplanowane.setText("Zaplanowane");
        jZaplanowane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jZaplanowaneMouseClicked(evt);
            }
        });
        jMenuBar1.add(jZaplanowane);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(filler3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 263, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jObraz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jWyszukajButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(4, 4, 4)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(200, 200, 200)
                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jObraz, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(filler3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jWyszukajButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
    
    private void rankTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rankTableMouseClicked
        int currentRow = rankTable.getSelectedRow();
        jTextField1.setText(rankTable.getValueAt(currentRow, 0).toString());
        jTextField2.setText(rankTable.getValueAt(currentRow, 1).toString());
        //jTextField3.setText(rankTable.getValueAt(currentRow, 2).toString());
        jTextField4.setText(rankTable.getValueAt(currentRow, 2).toString());
        jTextField5.setText(rankTable.getValueAt(currentRow, 3).toString());
        jTextField6.setText(rankTable.getValueAt(currentRow, 4).toString());
        //idZespolu= dr.getId_druzyny();
        pozycjaZaznaczona=true;
        
        
        idZawodnika  =  Integer.parseInt(rankTable.getModel().getValueAt(currentRow, 7).toString());
        
        
        jComboBox.removeAllItems();
        
        String stadion = rankTable.getValueAt(currentRow, 5).toString();
        jComboBox.addItem(stadion); 
        
        Zawodnik s = new Zawodnik();
        try {
            ArrayList<Zawodnik> listaZawodnikow = s.getLista();
            
            Collections.sort(listaZawodnikow, new Comparator<Zawodnik>() {
                public int compare(Zawodnik o1, Zawodnik o2) {
                    return o1.getNazwisko().compareTo(o2.getNazwisko());
                    }
                });
            
            for(Zawodnik st: listaZawodnikow)
            {
                   jComboBox.addItem(st.getNazwisko() + "," + st.getId_zawodnika());
            }
                
        } catch (SQLException ex) {
            Logger.getLogger(Miotly.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rankTableMouseClicked

    private void jDodajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDodajButtonActionPerformed
        if (!czyNazwaPusta())
        {
            Miotla miotla = new Miotla();
            ArrayList<Miotla> listaMiotel = new ArrayList<>();
            miotla.setModel(jTextField1.getText());
            miotla.setPredkosc(Float.parseFloat(jTextField2.getText()));
            miotla.setTworzywo(jTextField4.getText());
            
            miotla.setMasa(Float.parseFloat(jTextField5.getText()));
            miotla.setKolor(jTextField6.getText());

            try {
                listaMiotel = miotla.getLista();
            } catch (SQLException ex) {
                Logger.getLogger(Miotly.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            String nazwaZawodnika =(String)jComboBox.getSelectedItem();
            String[] parts = nazwaZawodnika.split(",");
            miotla.setZawodnik_id_zawodnika(Integer.parseInt(parts[1]));
     
            try {
            miotla.addQuery();

            } catch (SQLException ex) {
                Logger.getLogger(Miotly.class.getName()).log(Level.SEVERE, null, ex);
            }


            try {
                wypelnijTabele();
            } catch (SQLException ex) {
                Logger.getLogger(Miotly.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
    }//GEN-LAST:event_jDodajButtonActionPerformed

    private void jModyfikujButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jModyfikujButtonActionPerformed
            
            if(!pozycjaZaznaczona)
            {
                JOptionPane.showMessageDialog(new Frame(), "Proszę wybrać miotłę z tabeli, którą chcesz zaktualizować.", "BŁĄD", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            int currentRow = rankTable.getSelectedRow();    
            Miotla miotla = new Miotla();
            String nazwaZawodnika =(String)jComboBox.getSelectedItem();
            String[] parts;
            
            if(!nazwaZawodnika.equals(rankTable.getModel().getValueAt(currentRow, 5).toString()))
            {
                parts = nazwaZawodnika.split(",");
                idZawodnika=Integer.parseInt(parts[1]);
            }
            
            
            try {                
                miotla.updateQuery(Integer.parseInt(rankTable.getModel().getValueAt(currentRow, 6).toString()), jTextField1.getText(), 
                        Float.parseFloat(jTextField2.getText()), jTextField4.getText(), Float.parseFloat(jTextField5.getText()), jTextField6.getText(), idZawodnika);
                
            } catch (SQLException ex) {
                Logger.getLogger(Miotly.class.getName()).log(Level.SEVERE, null, ex);
            }
 
//            DefaultTableModel model = (DefaultTableModel) rankTable.getModel();
//            model.fireTableDataChanged();
//            rankTable.repaint();
            pozycjaZaznaczona=false;
            
            try {
                wypelnijTabele();
            } catch (SQLException ex) {
                Logger.getLogger(Miotly.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jModyfikujButtonActionPerformed

    private void jUsunButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUsunButtonActionPerformed
        
        try {
            if(!pozycjaZaznaczona)
            {
                JOptionPane.showMessageDialog(new Frame(), "Proszę wybrać miotłę z tabeli, którą chcesz usunąć.", "BŁĄD", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            int currentRow = rankTable.getSelectedRow();
            if (JOptionPane.showConfirmDialog(null,
                    "Czy na pewno chcesz nieodwracalnie usunąć zaznaczoną miotłę?", "Usunąć?",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION){
                Miotla d = new Miotla();
                int czyUsunieto=-1;
                
                    czyUsunieto = d.delQuery(Integer.parseInt(rankTable.getModel().getValueAt(currentRow, 6).toString()));
                    
                switch(czyUsunieto)
                {
                    case 1:  JOptionPane.showMessageDialog(new Frame(), "Pomyślnie usunięto miotłę.", "Sukces", JOptionPane.INFORMATION_MESSAGE);
                    break;
                    default: JOptionPane.showMessageDialog(new Frame(), "Coś poszło nie tak.", "BŁĄD", JOptionPane.INFORMATION_MESSAGE);
                    break;
                }
            }
            pozycjaZaznaczona=false;
//        DefaultTableModel model = (DefaultTableModel) rankTable.getModel();
//        model.fireTableDataChanged();
//        rankTable.repaint();
            wypelnijTabele();
        } catch (SQLException ex) {
            Logger.getLogger(Miotly.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jUsunButtonActionPerformed

    private void jWyszukajButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jWyszukajButton1ActionPerformed
        try {
            Miotla d = new Miotla();
            wyszukiwanie=true;
            wypelnijTabele();
            
        } catch (SQLException ex) {
            Logger.getLogger(Miotly.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jWyszukajButton1ActionPerformed

    private void jZawodnicyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jZawodnicyMouseClicked
        try {
            Zawodnicy t = new Zawodnicy();
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(Miotly.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jZawodnicyMouseClicked

    private void jStadionyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jStadionyMouseClicked
        try {
            Stadiony t = new Stadiony();
        } catch (SQLException ex) {
            Logger.getLogger(Miotly.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
      
    }//GEN-LAST:event_jStadionyMouseClicked

    private void jMiotlyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMiotlyMouseClicked
       
    }//GEN-LAST:event_jMiotlyMouseClicked

    private void jPracownicyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPracownicyMouseClicked
        try {
            Pracownicy t = new Pracownicy();
        } catch (SQLException ex) {
            Logger.getLogger(Miotly.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_jPracownicyMouseClicked

    private void jSedziowieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSedziowieMouseClicked
        try {
            Sedziowie t = new Sedziowie();
        } catch (SQLException ex) {
            Logger.getLogger(Miotly.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_jSedziowieMouseClicked

    private void jZniczeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jZniczeMouseClicked
        try {
            Znicze t = new Znicze();
        } catch (SQLException ex) {
            Logger.getLogger(Miotly.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_jZniczeMouseClicked

    private void jKaryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jKaryMouseClicked
        try {
            Kary t = new Kary();
        } catch (SQLException ex) {
            Logger.getLogger(Miotly.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_jKaryMouseClicked

    private void jRozegraneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRozegraneMouseClicked
        try {
            Rozegrane t = new Rozegrane();
        } catch (SQLException ex) {
            Logger.getLogger(Miotly.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose(); 
    }//GEN-LAST:event_jRozegraneMouseClicked

    private void jZaplanowaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jZaplanowaneMouseClicked
        try {
            Zaplanowane t = new Zaplanowane();
        } catch (SQLException ex) {
            Logger.getLogger(Miotly.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose(); 
    }//GEN-LAST:event_jZaplanowaneMouseClicked

    private void jRankingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRankingMouseClicked
        try {
            Ranking t = new Ranking();
        } catch (SQLException ex) {
            Logger.getLogger(Miotly.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jRankingMouseClicked

    public Boolean czyNazwaPusta()
    {
        if(jTextField1.getText().equals(""))
        {
            JOptionPane.showMessageDialog(new Frame(), "Nazwa nie może być pusta!", "BŁĄD", JOptionPane.INFORMATION_MESSAGE);
            return true;
        }
        return false;  
    }
    
    public void wypelnijTabele() throws SQLException
    {
        
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        defaultTableModel.addColumn("Model");
        defaultTableModel.addColumn("Predkość");
        defaultTableModel.addColumn("Tworzywo");
        defaultTableModel.addColumn("Masa");
        defaultTableModel.addColumn("Kolor");
        defaultTableModel.addColumn("Właściciel");
        defaultTableModel.addColumn("Id_miotly");
        defaultTableModel.addColumn("Id_zawodnika");

        Miotla d = new Miotla();
        ArrayList<Miotla> listaMiotel = new ArrayList<>();
        if(!wyszukiwanie)
            listaMiotel = d.getLista();
        else
            listaMiotel = d.wyszukaj(jTextField3.getText());

         Collections.sort(listaMiotel, new Comparator<Miotla>() {
            public int compare(Miotla o1, Miotla o2) {
                return o1.getModel().compareTo(o2.getModel());
                }
            });

         
        Zawodnik s = new Zawodnik();
        ArrayList<Zawodnik> listaZawodnikow = s.getLista();
                
        for(Miotla dr: listaMiotel)
        {
            String nazwisko=null;
            String ID=null;
            for(Zawodnik st: listaZawodnikow)
            {
                if(dr.getZawodnik_id_zawodnika().equals(st.getId_zawodnika()))
                {
                    nazwisko=st.getNazwisko()+","+st.getId_zawodnika();
                    ID=st.getId_zawodnika().toString();
                    break;
                }
            }
            defaultTableModel.addRow(new Object[] {dr.getModel(),dr.getPredkosc().toString(),dr.getTworzywo(), dr.getMasa().toString(), dr.getKolor(), nazwisko, dr.getId_miotly(), ID});
        }

        rankTable.setModel(defaultTableModel);
        rankTable.getColumnModel().getColumn(3).setPreferredWidth(15);


        rankTable.removeColumn(rankTable.getColumnModel().getColumn(7));
        rankTable.removeColumn(rankTable.getColumnModel().getColumn(6));
                
    }
    
    
    public void fillData() throws SQLException {

                //Wysrodkuj
                Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
                this.setLocation((dim.width-this.getSize().width)/2, (dim.height-this.getSize().height)/2); 
        
                jTextField1.setColumns(10);
                jTextField2.setColumns(10);
                //jTextField4.setColumns(10);
                try{
//                    ImageIcon img = new ImageIcon(getClass().getResource("/img/pracownicy.png"));
//                    Image image = img.getImage(); // transform it 
//                    Image newimg = image.getScaledInstance(271, 190,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
//                    img = new ImageIcon(newimg);
//                    jObraz.setIcon(img);
                    jObraz.setIcon(new ImageIcon(getClass().getResource("/img/miotla.png")));
                }catch(Exception e){ System.out.println("Nie znaleziono zdjęcia\n");} 
                setResizable(false);
                
                //uzupelnij comboBox
                Zawodnik s = new Zawodnik();
                ArrayList<Zawodnik> listaZawodnikow = s.getLista();
                
                Collections.sort(listaZawodnikow, new Comparator<Zawodnik>() {
                    public int compare(Zawodnik o1, Zawodnik o2) {
                        return o1.getNazwisko().compareTo(o2.getNazwisko());
                        }
                    });
            
                jComboBox.removeAllItems();
                
                for(Zawodnik st: listaZawodnikow)
                {
                    jComboBox.addItem(st.getNazwisko() + "," + st.getId_zawodnika() );
                }
                //jComboBox.
                wypelnijTabele();
                //jObraz.setIcon((Icon) Toolkit.getDefaultToolkit().getImage("src/img/znicz.jpg"));
		
            }  
    /**
     * @param args the command line arguments
     */
    

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
                        //in.wyswietl();
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Miotly.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Miotly.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Miotly.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Miotly.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>        
        //</editor-fold>        
        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                try {
                    new Miotly().setVisible(true);
                    
                    //Ranking.rankTable.add("J","K","L","O");
                } catch (SQLException ex) {
                    Logger.getLogger(Miotly.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        });
 
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JComboBox<String> jComboBox;
    private java.awt.Button jDodajButton;
    private javax.swing.JMenu jKary;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jMiotly;
    private java.awt.Button jModyfikujButton;
    private javax.swing.JLabel jObraz;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu jPracownicy;
    private javax.swing.JMenu jRanking;
    private javax.swing.JMenu jRozegrane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu jSedziowie;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenu jStadiony;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private java.awt.Button jUsunButton;
    private javax.swing.JToggleButton jWyszukajButton1;
    private javax.swing.JMenu jZaplanowane;
    private javax.swing.JMenu jZawodnicy;
    private javax.swing.JMenu jZnicze;
    private javax.swing.JTable rankTable;
    // End of variables declaration//GEN-END:variables
}
