/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quidditch;

import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Date;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.*;

/**
 *
 * @author Elater
 */
public class Stadiony extends javax.swing.JFrame {
    
    Boolean pozycjaZaznaczona=false;
    Integer idDruzyny;
    Integer idStadiona;
    Boolean wyszukiwanie=false;
    /**
     * Creates new form Ranking
     */
    public Stadiony() throws SQLException {
        initComponents();
        fillData();
        setVisible(true);
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent we) {
                int odp = JOptionPane.showConfirmDialog(null, "Czy na pewno chcesz zamknąć aplikację?", "Zamknąć?", JOptionPane.YES_NO_OPTION);
                if (odp ==JOptionPane.YES_OPTION)
                    System.exit(0);
            }
            
});
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        rankTable = new javax.swing.JTable();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 40), new java.awt.Dimension(0, 40), new java.awt.Dimension(32767, 40));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 30), new java.awt.Dimension(0, 30), new java.awt.Dimension(32767, 30));
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jObraz = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jWyszukajButton1 = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox = new javax.swing.JComboBox<>();
        jUsunButton = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jModyfikujButton = new java.awt.Button();
        jLabel5 = new javax.swing.JLabel();
        jDodajButton = new java.awt.Button();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jRanking = new javax.swing.JMenu();
        jZawodnicy = new javax.swing.JMenu();
        jStadiony = new javax.swing.JMenu();
        jMiotly = new javax.swing.JMenu();
        jPracownicy = new javax.swing.JMenu();
        jSedziowie = new javax.swing.JMenu();
        jZnicze = new javax.swing.JMenu();
        jKary = new javax.swing.JMenu();
        jRozegrane = new javax.swing.JMenu();
        jZaplanowane = new javax.swing.JMenu();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quidditch rank");

        rankTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Szubinianka", "Polska", "Szubinland", "66"},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nazwa", "Narodowość", "Stadion", "Punkty"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        rankTable.setName("tabelaRanking"); // NOI18N
        rankTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rankTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(rankTable);

        jWyszukajButton1.setText("Wyszukaj");
        jWyszukajButton1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jWyszukajButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jWyszukajButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Pojemność:");

        jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jUsunButton.setLabel("Usuń");
        jUsunButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUsunButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Nazwa:");

        jModyfikujButton.setLabel("Modyfikuj");
        jModyfikujButton.setName(""); // NOI18N
        jModyfikujButton.setPreferredSize(new java.awt.Dimension(50, 24));
        jModyfikujButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jModyfikujButtonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Parking:");

        jDodajButton.setActionCommand("Dodaj");
        jDodajButton.setLabel("Dodaj");
        jDodajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDodajButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Adres:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jDodajButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jModyfikujButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                                .addComponent(jUsunButton, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                    .addComponent(jTextField2)))
                            .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(36, 36, 36)
                        .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDodajButton, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jModyfikujButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jUsunButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jRanking.setText("Ranking");
        jRanking.setBorderPainted(true);
        jRanking.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jRanking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRankingMouseClicked(evt);
            }
        });
        jMenuBar1.add(jRanking);

        jZawodnicy.setText("Zawodnicy");
        jZawodnicy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jZawodnicyMouseClicked(evt);
            }
        });
        jMenuBar1.add(jZawodnicy);

        jStadiony.setText("Stadiony");
        jStadiony.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jStadionyMouseClicked(evt);
            }
        });
        jMenuBar1.add(jStadiony);

        jMiotly.setText("Miotly");
        jMiotly.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMiotlyMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMiotly);

        jPracownicy.setText("Pracownicy");
        jPracownicy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPracownicyMouseClicked(evt);
            }
        });
        jMenuBar1.add(jPracownicy);

        jSedziowie.setText("Sędziowie");
        jSedziowie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSedziowieMouseClicked(evt);
            }
        });
        jMenuBar1.add(jSedziowie);

        jZnicze.setText("Znicze");
        jZnicze.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jZniczeMouseClicked(evt);
            }
        });
        jMenuBar1.add(jZnicze);

        jKary.setText("Kary");
        jKary.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jKaryMouseClicked(evt);
            }
        });
        jMenuBar1.add(jKary);

        jRozegrane.setText("Rozegrane");
        jRozegrane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRozegraneMouseClicked(evt);
            }
        });
        jMenuBar1.add(jRozegrane);

        jZaplanowane.setText("Zaplanowane");
        jZaplanowane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jZaplanowaneMouseClicked(evt);
            }
        });
        jMenuBar1.add(jZaplanowane);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(filler3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jWyszukajButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)))
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jSeparator1)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jObraz, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addContainerGap())))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(183, 183, 183)
                                .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jObraz, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filler3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jWyszukajButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
    
    private void rankTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rankTableMouseClicked
        int currentRow = rankTable.getSelectedRow();
        jTextField1.setText(rankTable.getValueAt(currentRow, 0).toString());
        jTextField2.setText(rankTable.getValueAt(currentRow, 1).toString());
        //jTextField3.setText(rankTable.getValueAt(currentRow, 2).toString());
        jTextField4.setText(rankTable.getValueAt(currentRow, 2).toString());
        //idDruzyny= dr.getId_druzyny();
        pozycjaZaznaczona=true;
           
        
        jComboBox.removeAllItems();
        
        jComboBox.addItem(rankTable.getValueAt(currentRow, 3).toString()); 
        jComboBox.addItem("T"); 
        jComboBox.addItem("N");   
      
    }//GEN-LAST:event_rankTableMouseClicked

    private void jDodajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDodajButtonActionPerformed
        if (!czyNazwaPusta())
        {
            ArrayList<Stadion> listaStadionow= new ArrayList<>();
            try {
                listaStadionow = Stadion.getLista();
            } catch (SQLException ex) {
                Logger.getLogger(Stadiony.class.getName()).log(Level.SEVERE, null, ex);
            }
             for(Stadion dr: listaStadionow)
            {
                if(dr.getNazwa().equals(jTextField1.getText()))
                {
                    JOptionPane.showMessageDialog(new Frame(), "Stadion z taką nazwą już istnieje!", "BŁĄD", JOptionPane.INFORMATION_MESSAGE);
                    return;
                }
            }
            Stadion stadion = new Stadion();
            stadion.setNazwa(jTextField1.getText());


            stadion.setAdres(jTextField2.getText());

            int pojemnosc =Integer.parseInt(jTextField4.getText());
            stadion.setPojemnosc(pojemnosc);
            stadion.setParking((String)jComboBox.getSelectedItem());
                                             
            try {
            stadion.addQuery();

            DefaultTableModel model = (DefaultTableModel)rankTable.getModel();

            wypelnijTabele();
            
            } catch (SQLException ex) {
                Logger.getLogger(Stadiony.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
        
    }//GEN-LAST:event_jDodajButtonActionPerformed

    
    private void jModyfikujButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jModyfikujButtonActionPerformed
            
            if(!pozycjaZaznaczona)
            {
                JOptionPane.showMessageDialog(new Frame(), "Proszę wybrać stadion z tabeli, którego chcesz zaktualizować.", "BŁĄD", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            int currentRow = rankTable.getSelectedRow();    
            Stadion stadion = new Stadion();
            
            int ID=Integer.parseInt(rankTable.getModel().getValueAt(currentRow, 4).toString());
            
        try { 
            stadion.updateQuery(ID, jTextField1.getText(), jTextField2.getText(),Integer.parseInt(jTextField4.getText()),
                    jComboBox.getSelectedItem().toString());
        } catch (SQLException ex) {
            Logger.getLogger(Stadiony.class.getName()).log(Level.SEVERE, null, ex);
        }
 
            pozycjaZaznaczona=false;
            
            try {
                wypelnijTabele();
            } catch (SQLException ex) {
                Logger.getLogger(Stadiony.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_jModyfikujButtonActionPerformed

    private void jUsunButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUsunButtonActionPerformed
        
        try {
            if(!pozycjaZaznaczona)
            {
                JOptionPane.showMessageDialog(new Frame(), "Proszę wybrać drużynę z tabeli, którą chcesz usunąć.", "BŁĄD", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            int currentRow = rankTable.getSelectedRow();
            if (JOptionPane.showConfirmDialog(null,
                    "Czy na pewno chcesz nieodwracalnie usunąć zaznaczoną drużynę?", "Usunąć?",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION){
                Stadion d = new Stadion();
                int czyUsunieto=0;
                
                    czyUsunieto = d.delQuery(Integer.parseInt(rankTable.getModel().getValueAt(currentRow, 4).toString()));
                    
                switch(czyUsunieto)
                {
                    case -1: JOptionPane.showMessageDialog(new Frame(), "Nie można usunąć stadionu, ponieważ istnieje drużyna do której należy ten stadion", "Usuń najpierw powiązaną drużynę", JOptionPane.INFORMATION_MESSAGE);
                                break;   
                    case 1: JOptionPane.showMessageDialog(new Frame(), "Pomyślnie usunięto stadion", "SUKCES", JOptionPane.INFORMATION_MESSAGE);
                                break;                  
                    default: JOptionPane.showMessageDialog(new Frame(), "Coś poszło nie tak.", "BŁĄD", JOptionPane.INFORMATION_MESSAGE);
                    break;
                }
            }
            pozycjaZaznaczona=false;
//        DefaultTableModel model = (DefaultTableModel) rankTable.getModel();
//        model.fireTableDataChanged();
//        rankTable.repaint();
            wypelnijTabele();
        } catch (SQLException ex) {
            Logger.getLogger(Stadiony.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jUsunButtonActionPerformed

    private void jWyszukajButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jWyszukajButton1ActionPerformed
        try {
            Stadion d = new Stadion();
            wyszukiwanie=true;
            wypelnijTabele();
            
        } catch (SQLException ex) {
            Logger.getLogger(Stadiony.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jWyszukajButton1ActionPerformed

    private void jRankingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRankingMouseClicked
        try {
            Ranking t = new Ranking();
        } catch (SQLException ex) {
            Logger.getLogger(Stadiony.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_jRankingMouseClicked

    private void jZawodnicyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jZawodnicyMouseClicked
        try {
            Zawodnicy zawodnicy = new Zawodnicy();
        } catch (SQLException ex) {
            Logger.getLogger(Stadiony.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_jZawodnicyMouseClicked

    private void jStadionyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jStadionyMouseClicked
        
    }//GEN-LAST:event_jStadionyMouseClicked

    private void jMiotlyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMiotlyMouseClicked
        try {
            Miotly t = new Miotly();
        } catch (SQLException ex) {
            Logger.getLogger(Stadiony.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_jMiotlyMouseClicked

    private void jPracownicyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPracownicyMouseClicked
         try {
            Pracownicy t = new Pracownicy();
        } catch (SQLException ex) {
            Logger.getLogger(Stadiony.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_jPracownicyMouseClicked

    private void jSedziowieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSedziowieMouseClicked
         try {
            Sedziowie t = new Sedziowie();
        } catch (SQLException ex) {
            Logger.getLogger(Stadiony.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_jSedziowieMouseClicked

    private void jZniczeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jZniczeMouseClicked
         try {
            Znicze t = new Znicze();
        } catch (SQLException ex) {
            Logger.getLogger(Stadiony.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_jZniczeMouseClicked

    private void jKaryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jKaryMouseClicked
         try {
            Kary t = new Kary();
        } catch (SQLException ex) {
            Logger.getLogger(Stadiony.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_jKaryMouseClicked

    private void jRozegraneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRozegraneMouseClicked
         try {
            Rozegrane t = new Rozegrane();
        } catch (SQLException ex) {
            Logger.getLogger(Stadiony.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_jRozegraneMouseClicked

    private void jZaplanowaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jZaplanowaneMouseClicked
        try {
            Zaplanowane t = new Zaplanowane();
        } catch (SQLException ex) {
            Logger.getLogger(Stadiony.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_jZaplanowaneMouseClicked

    public Boolean czyNazwaPusta()
    {
        if(jTextField1.getText().equals(""))
        {
            JOptionPane.showMessageDialog(new Frame(), "Nazwisko nie może być puste!", "BŁĄD", JOptionPane.INFORMATION_MESSAGE);
            return true;
        }
        return false;  
    }
    
    public void wypelnijTabele() throws SQLException
    {
        
        DefaultTableModel defaultTableModel = new DefaultTableModel();
        defaultTableModel.addColumn("Nazwa");
        defaultTableModel.addColumn("Adres");
        defaultTableModel.addColumn("Pojemność");
        defaultTableModel.addColumn("Parking");
        defaultTableModel.addColumn("Id_stadionu");

        Stadion d = new Stadion();
        ArrayList<Stadion> listaStadionow = new ArrayList<>();
        if(!wyszukiwanie)
            listaStadionow = d.getLista();
        else
            listaStadionow = d.wyszukaj(jTextField3.getText());

         Collections.sort(listaStadionow, new Comparator<Stadion>() {
            public int compare(Stadion o1, Stadion o2) {
                return o1.getNazwa().compareTo(o2.getNazwa());
                }
            });
         
         
        for(Stadion dr: listaStadionow)
        {            
            defaultTableModel.addRow(new Object[] {dr.getNazwa(),dr.getAdres(),dr.getPojemnosc(),dr.getParking(), dr.getId_stadionu()});
        }

        rankTable.setModel(defaultTableModel);
        rankTable.getColumnModel().getColumn(3).setPreferredWidth(15);


        rankTable.removeColumn(rankTable.getColumnModel().getColumn(4));
                
    }
    
    
    public void fillData() throws SQLException {

                //Wysrodkuj
                Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
                this.setLocation((dim.width-this.getSize().width)/2, (dim.height-this.getSize().height)/2); 
        
                jTextField1.setColumns(10);
                jTextField2.setColumns(10);
                jTextField4.setColumns(10);
                try{
//                    ImageIcon img = new ImageIcon(getClass().getResource("/img/pracownicy.png"));
//                    Image image = img.getImage(); // transform it 
//                    Image newimg = image.getScaledInstance(271, 190,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way  
//                    img = new ImageIcon(newimg);
//                    jObraz.setIcon(img);
                    jObraz.setIcon(new ImageIcon(getClass().getResource("/img/stadion.png")));
                }catch(Exception e){ System.out.println("Nie znaleziono zdjęcia\n");} 
                setResizable(false);
                            
                
                
                jComboBox.removeAllItems();
                jComboBox.setPrototypeDisplayValue("10");
                //jComboBox3.setPreferredSize(dim);

                jComboBox.addItem("TAK");
                jComboBox.addItem("NIE");      

                wypelnijTabele();
		
            }  
    /**
     * @param args the command line arguments
     */
    

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
                        //in.wyswietl();
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stadiony.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stadiony.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stadiony.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stadiony.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>        
        //</editor-fold>        
        //</editor-fold>        
        //</editor-fold>        
        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                try {
                    new Stadiony().setVisible(true);
                    
                    //Ranking.rankTable.add("J","K","L","O");
                } catch (SQLException ex) {
                    Logger.getLogger(Stadiony.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        });
 
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JComboBox<String> jComboBox;
    private java.awt.Button jDodajButton;
    private javax.swing.JMenu jKary;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jMiotly;
    private java.awt.Button jModyfikujButton;
    private javax.swing.JLabel jObraz;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu jPracownicy;
    private javax.swing.JMenu jRanking;
    private javax.swing.JMenu jRozegrane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenu jSedziowie;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JMenu jStadiony;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private java.awt.Button jUsunButton;
    private javax.swing.JToggleButton jWyszukajButton1;
    private javax.swing.JMenu jZaplanowane;
    private javax.swing.JMenu jZawodnicy;
    private javax.swing.JMenu jZnicze;
    private javax.swing.JTable rankTable;
    // End of variables declaration//GEN-END:variables
}
